# Generated by Django 5.0.2 on 2024-03-11 09:18

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='static/assets/user/user.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, 400], upload_to='users/avatars/', verbose_name='Фото пользователя'),
        ),
    ]
