# Generated by Django 5.0.2 on 2024-03-16 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=255, verbose_name='Класс отоброжение')),
                ('path_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url name')),
            ],
            options={
                'verbose_name': 'Окно доступа',
                'verbose_name_plural': 'Окна доступов',
            },
        ),
        migrations.CreateModel(
            name='ViewPermissionRuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.SmallIntegerField(default=30, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Категория доступа',
                'verbose_name_plural': 'Категории доступов',
            },
        ),
        migrations.CreateModel(
            name='ViewPermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.SmallIntegerField(default=30, verbose_name='Позиция')),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_rule', to='user.viewpermission', verbose_name='Окно доступа')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_rule', to='user.viewpermissionrulecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступы',
            },
        ),
        migrations.CreateModel(
            name='ViewPermissionRuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('permissions', models.ManyToManyField(to='user.viewpermissionrule', verbose_name='Доступы')),
            ],
            options={
                'verbose_name': 'Группа доступа',
                'verbose_name_plural': 'Группы доступов',
            },
        ),
        migrations.CreateModel(
            name='ViewPermissionRuleGroupToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.viewpermissionrulegroup', verbose_name='Доступ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_groups', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Группа доступа',
                'verbose_name_plural': 'Группы доступов',
            },
        ),
        migrations.CreateModel(
            name='ViewPermissionRuleToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.viewpermissionrule', verbose_name='Доступ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступа',
                'verbose_name_plural': 'Доступы',
            },
        ),
    ]
