# Generated by Django 5.0.2 on 2024-04-01 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_is_composite'),
        ('user', '0004_viewpermission_viewpermissionrulecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='product.industry', verbose_name='Отрасль'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('MANAGER', 'Менеджер')], default='ADMIN', max_length=255, verbose_name='Тип пользователя'),
            preserve_default=False,
        ),
    ]
