# Generated by Django 5.0.2 on 2024-04-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_workerincomes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerincomes',
            options={'ordering': ('-created_at',), 'verbose_name': 'Насичление сотрудкику', 'verbose_name_plural': 'Насичления сотрудкику'},
        ),
        migrations.AddField(
            model_name='user',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Зарплата'),
        ),
    ]
