# Generated by Django 5.0.2 on 2024-04-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_type_alter_workerincomes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('SALESMAN', 'Продавец'), ('FLORIST', 'Флорист с фиксированной платой'), ('FLORIST_PERCENT', 'Флорист с процентной платой'), ('MANAGER', 'Менеджер'), ('WAREHOUSE_MASTER', 'Зав. склад')], max_length=255, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='workerincomes',
            name='type',
            field=models.CharField(choices=[('PRODUCT_SALE', 'Продажа товара'), ('PRODUCT_FACTORY_SALE', 'Продажа букета'), ('PRODUCT_FACTORY_CREATE', 'Создание букета'), ('BONUS', 'Премия'), ('SALARY', 'Зарплата'), ('FINE', 'Штраф')], max_length=255, verbose_name='Тип начисления'),
        ),
    ]
