# Generated by Django 5.0.2 on 2024-05-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_workerincomes_type_workerincomes_income_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='penalty_count',
            field=models.IntegerField(default=0, verbose_name='Текущее кол-во штрафных букетов'),
        ),
    ]
