# Generated by Django 5.0.2 on 2024-05-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_penalty_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='penalty_count',
        ),
    ]
