# Generated by Django 5.0.2 on 2024-05-15 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0028_alter_productfactory_name'),
        ('user', '0017_floristpenalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='floristpenalty',
            name='product_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='factory.productfactory', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='floristpenalty',
            name='count',
            field=models.IntegerField(default=2, verbose_name='Кол-во'),
        ),
    ]
