# Generated by Django 5.0.2 on 2024-05-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0029_productfactory_is_penalty'),
        ('user', '0019_alter_floristpenalty_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floristpenalty',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='floristpenalty',
            name='product_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='factory.productfactory', unique=True, verbose_name='Букет'),
        ),
    ]
