# Generated by Django 5.0.2 on 2024-05-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_floristpenalty_product_factory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FloristPenalty',
        ),
    ]
