# Generated by Django 5.0.2 on 2024-03-26 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0004_alter_warehouseproductwriteoff_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('self_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Себестоимость')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена продажи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finished', models.BooleanField(default=False, verbose_name='Закончено')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('written_off', models.BooleanField(default=False, verbose_name='Списан')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_user_product_factory_set', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('deleted_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_user_product_factory_set', to=settings.AUTH_USER_MODEL, verbose_name='Удалил')),
                ('finished_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_user_product_factory_set', to=settings.AUTH_USER_MODEL, verbose_name='Закончил')),
            ],
            options={
                'verbose_name': ['Производство товара'],
                'verbose_name_plural': ['Производство товаров'],
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFactoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Кол-во')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_factory_item_set', to='factory.productfactory', verbose_name='Производство')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_factory_item_set', to='warehouse.warehouseproduct', verbose_name='Товар со склада')),
            ],
            options={
                'verbose_name': 'Элемент производства',
                'verbose_name_plural': 'Элементы производства',
                'ordering': ['-id'],
            },
        ),
    ]
