# Generated by Django 5.0.2 on 2024-03-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactory',
            name='product_code',
            field=models.CharField(default=0, max_length=255, unique=True, verbose_name='Код'),
            preserve_default=False,
        ),
    ]
