# Generated by Django 5.0.2 on 2024-03-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_productfactory_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactory',
            name='type',
            field=models.CharField(choices=[('FLOWERS', 'Цветочный'), ('SWEETS', 'Сладкий')], default='FLOWERS', max_length=255, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
