# Generated by Django 5.0.2 on 2024-03-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_remove_productfactory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfactory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Цена продажи'),
        ),
    ]
