# Generated by Django 5.0.2 on 2024-03-26 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_alter_productfactory_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfactory',
            name='deleted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_user_product_factory_set', to=settings.AUTH_USER_MODEL, verbose_name='Удалил'),
        ),
        migrations.AlterField(
            model_name='productfactory',
            name='finished_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_user_product_factory_set', to=settings.AUTH_USER_MODEL, verbose_name='Закончил'),
        ),
    ]
