# Generated by Django 5.0.2 on 2024-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_alter_productfactory_deleted_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfactory',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Код'),
        ),
    ]
