# Generated by Django 5.0.2 on 2024-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_alter_productfactory_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfactory',
            name='self_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Себестоимость'),
        ),
    ]
