# Generated by Django 5.0.2 on 2024-03-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0011_alter_productfactoryitem_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfactory',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='productfactory',
            name='written_off',
        ),
        migrations.AddField(
            model_name='productfactory',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('FINISHED', 'Завершен'), ('SOLD', 'Продан'), ('CANCELLED', 'Отменен'), ('WRITTEN_OFF', 'Списан')], default='CREATED', max_length=255, verbose_name='Статус'),
        ),
    ]
