# Generated by Django 5.0.2 on 2024-03-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0012_remove_productfactory_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfactory',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('FINISHED', 'Завершен'), ('SOLD', 'Продан'), ('WRITTEN_OFF', 'Списан')], default='CREATED', max_length=255, verbose_name='Статус'),
        ),
    ]
