# Generated by Django 5.0.2 on 2024-04-04 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0016_alter_productfactory_options_productfactory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactory',
            name='florist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='owner_product_factory_set', to=settings.AUTH_USER_MODEL, verbose_name='Флорист'),
            preserve_default=False,
        ),
    ]
