# Generated by Django 5.0.2 on 2024-04-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0018_productfactory_sales_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfactory',
            name='sales_type',
            field=models.CharField(choices=[('STORE', 'Магазин'), ('SHOWCASE', 'Витрина'), ('CONGRATULATION', 'Поздравление')], max_length=255, verbose_name='Тип продажи товара'),
        ),
    ]
