# Generated by Django 5.0.2 on 2024-04-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0019_alter_productfactory_sales_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfactoryitem',
            name='total',
        ),
        migrations.AddField(
            model_name='productfactoryitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='productfactoryitem',
            name='total_self_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма себестоимости'),
        ),
    ]
