# Generated by Django 5.0.2 on 2024-04-25 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0023_productfactoryitemreturn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfactoryitemreturn',
            options={'ordering': ['-created_at'], 'verbose_name': 'Возвращенный элемент производства', 'verbose_name_plural': 'Возвращенные элемент производства'},
        ),
        migrations.AlterField(
            model_name='productfactoryitemreturn',
            name='factory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_returns', to='factory.productfactoryitem', verbose_name='Элемент производства'),
        ),
    ]
