# Generated by Django 5.0.2 on 2024-04-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0024_alter_productfactoryitemreturn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Кол-во'),
        ),
    ]
