# Generated by Django 5.0.2 on 2024-05-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0028_alter_productfactory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactory',
            name='is_penalty',
            field=models.BooleanField(default=False, verbose_name='Штрафной?'),
        ),
    ]
