# Generated by Django 5.0.2 on 2024-05-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0031_productfactorycategory_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactorycategory',
            name='charge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Процент наценки'),
        ),
    ]
