# Generated by Django 5.0.2 on 2024-10-21 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0032_productfactorycategory_charge_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryTakeApartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Доставлен')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Отвечен')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Разрешение дано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_take_apart_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_take_apart_requests', to='factory.productfactory', verbose_name='Букет')),
            ],
        ),
    ]
