# Generated by Django 5.0.2 on 2025-03-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0034_factorytakeapartrequest_initial_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorytakeapartrequest',
            name='request_type',
            field=models.CharField(choices=[('TO_CREATE', 'Разборка'), ('WRITE_OFF', 'Списание'), ('FLORIST_CHANGE', 'Изменение флориста')], max_length=50, verbose_name='Тип запроса'),
        ),
    ]
