# Generated by Django 5.0.2 on 2024-03-05 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderitem_debt_orderitemproductoutcome'),
        ('product', '0006_category_is_deleted_industry_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='warehouse_product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.product', verbose_name='Товар со склада'),
            preserve_default=False,
        ),
    ]
