# Generated by Django 5.0.2 on 2024-03-06 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_orderitem_debt_order_debt'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemproductoutcome',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_outcomes', to='order.orderitem', verbose_name='Элемент заказа'),
        ),
        migrations.AlterField(
            model_name='orderitemproductoutcome',
            name='warehouse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_outcomes', to='warehouse.warehouseproduct', verbose_name='Товар'),
        ),
    ]
