# Generated by Django 5.0.2 on 2024-03-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
    ]
