# Generated by Django 5.0.2 on 2024-03-21 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_client_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_returns', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_returns', to='order.orderitem', verbose_name='Элемент заказа')),
            ],
        ),
    ]
