# Generated by Django 5.0.2 on 2024-03-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_orderitemproductreturn_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemproductreturn',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='orderitemproductreturn',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Количество'),
        ),
    ]
