# Generated by Django 5.0.2 on 2024-03-22 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderitemproductreturn_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemproductreturn',
            name='deleted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_returns_deleted_users', to=settings.AUTH_USER_MODEL, verbose_name='Удалил'),
        ),
        migrations.AddField(
            model_name='orderitemproductreturn',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='orderitemproductreturn',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_returns_created_users', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
    ]
