# Generated by Django 5.0.2 on 2024-03-29 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_orderitemproductfactory_is_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemproductreturn',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
