# Generated by Django 5.0.2 on 2024-04-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_orderitemproductreturn_count'),
        ('warehouse', '0004_alter_warehouseproductwriteoff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemproductoutcome',
            name='warehouse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_outcomes', to='warehouse.warehouseproduct', verbose_name='Товар'),
        ),
    ]
