# Generated by Django 5.0.2 on 2024-04-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_orderitemproductoutcome_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Скидка'),
        ),
    ]
