# Generated by Django 5.0.2 on 2024-04-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_orderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemproductfactory',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Скидка'),
        ),
    ]
