# Generated by Django 5.0.2 on 2024-04-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemproductreturn',
            name='total_self_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма себестоимости'),
        ),
    ]
