# Generated by Django 5.0.2 on 2024-05-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_orderitemproductreturn_total_self_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Цена'),
        ),
    ]
