# Generated by Django 5.0.2 on 2024-04-20 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_settings_product_sale_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='congratulations_product_factory_sale_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент с продажи букета для праздника'),
        ),
        migrations.AddField(
            model_name='settings',
            name='showcase_product_factory_sale_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент с продажи букета с витрины'),
        ),
        migrations.AddField(
            model_name='settings',
            name='store_product_factory_sale_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент с продажи букета'),
        ),
    ]
