# Generated by Django 5.0.2 on 2024-05-18 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_settings_product_factory_create_commission_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='multiple_product_sale_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент с продажи товаров из нескольких магазинов'),
        ),
    ]
