# Generated by Django 5.0.2 on 2024-05-18 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_settings_product_factory_charge_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='product_factory_sale_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент с продажи букета'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='congratulations_product_factory_sale_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент с продажи букета для праздника флористу'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='product_factory_create_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма компенсации флористу за создание букета'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='showcase_product_factory_sale_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент с продажи букета с витрины флористу'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='store_product_factory_sale_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент с продажи букета флористу'),
        ),
    ]
