# Generated by Django 5.0.2 on 2024-05-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_botmessages_botmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='congratulations_sweets_create_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма компенсации за создание набора из сладостей на поздравление'),
        ),
        migrations.AddField(
            model_name='settings',
            name='store_sweets_create_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма компенсации за создание набора из сладостей для магазина'),
        ),
    ]
