# Generated by Django 5.0.2 on 2024-10-31 12:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_settings_multiple_product_sale_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='write_off_permission_granted_industries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=[], size=None, verbose_name='Отрасли для которых разрешены списания'),
            preserve_default=False,
        ),
    ]
