# Generated by Django 5.0.2 on 2024-11-14 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_actionpermissionrequest'),
        ('factory', '0034_factorytakeapartrequest_initial_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequestTgMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(verbose_name='Chat id')),
                ('message_id', models.CharField(verbose_name='Message id')),
                ('action_permission_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.actionpermissionrequest', verbose_name='Обычный запрос')),
                ('factory_permission_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.factorytakeapartrequest', verbose_name='Запрос на действие с букетом')),
            ],
        ),
    ]
