# Generated by Django 5.0.2 on 2024-04-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_industry_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('SALESMAN', 'Продавец'), ('FLORIST', 'Флорист'), ('MANAGER', 'Менеджер')], max_length=255, verbose_name='Тип пользователя'),
        ),
    ]
