# Generated by Django 5.0.2 on 2024-04-12 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0021_alter_productfactoryitem_warehouse_product'),
        ('order', '0024_alter_orderitemproductoutcome_order_item'),
        ('user', '0008_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerIncomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма начисления')),
                ('type', models.CharField(choices=[('ORDER_SALE', 'Продажа'), ('PRODUCT_FACTORY_SALE', 'Продажа букета'), ('BONUS', 'Премия'), ('SALARY', 'Зарплата'), ('FINE', 'Штраф')], max_length=255, verbose_name='Тип начисления')),
                ('salary_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Информация о зарплате')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_incomes', to='order.order', verbose_name='Заказ')),
                ('product_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_incomes', to='factory.productfactory', verbose_name='Товар из производства')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_order_incomes', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
