# Generated by Django 5.0.2 on 2024-04-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_workerincomes_options_user_salary_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('SALESMAN', 'Продавец'), ('FLORIST', 'Флорист'), ('MANAGER', 'Менеджер'), ('WAREHOUSE_MASTER', 'Зав. склад')], max_length=255, verbose_name='Тип пользователя'),
        ),
    ]
