# Generated by Django 5.0.2 on 2024-04-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_type_alter_workerincomes_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerincomes',
            name='type',
        ),
        migrations.AddField(
            model_name='workerincomes',
            name='income_type',
            field=models.CharField(choices=[('INCOME', 'Доход'), ('OUTCOME', 'Расход')], default='INCOME', max_length=255, verbose_name='Тип начисления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerincomes',
            name='reason',
            field=models.CharField(choices=[('PRODUCT_SALE', 'Продажа товара'), ('PRODUCT_FACTORY_SALE', 'Продажа букета'), ('PRODUCT_FACTORY_CREATE', 'Создание букета'), ('BONUS', 'Премия'), ('SALARY', 'Зарплата'), ('FINE', 'Штраф')], default='PRODUCT_SALE', max_length=255, verbose_name='Причина начисления'),
            preserve_default=False,
        ),
    ]
