# Generated by Django 5.0.2 on 2024-05-15 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_user_penalty_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloristPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Кол-во')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('florist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL, verbose_name='Флорист')),
            ],
            options={
                'verbose_name': 'Штрафные букеты',
                'verbose_name_plural': 'Штрафные букеты',
                'ordering': ['created_at'],
            },
        ),
    ]
