# Generated by Django 5.0.2 on 2024-05-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0028_alter_productfactory_name'),
        ('user', '0018_floristpenalty_product_factory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floristpenalty',
            unique_together={('florist', 'product_factory')},
        ),
    ]
