# Generated by Django 5.0.2 on 2024-05-15 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0029_productfactory_is_penalty'),
        ('user', '0020_alter_floristpenalty_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floristpenalty',
            name='product_factory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='factory.productfactory', verbose_name='Букет'),
        ),
    ]
