# Generated by Django 5.0.2 on 2024-05-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_delete_floristpenalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('SALESMAN', 'Продавец'), ('FLORIST', 'Флорист с фиксированной платой'), ('FLORIST_PERCENT', 'Флорист с процентной платой'), ('MANAGER', 'Менеджер'), ('WAREHOUSE_MASTER', 'Зав. склад'), ('SWEETS_CRAFTER', 'Создатель сладостей')], max_length=255, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='workerincomes',
            name='reason',
            field=models.CharField(choices=[('PRODUCT_SALE', 'Совершил/а продажу'), ('PRODUCT_FACTORY_SALE', 'Продался букет'), ('PRODUCT_FACTORY_CREATE', 'Создание букета'), ('BONUS', 'Премия'), ('SALARY', 'Зарплата'), ('FINE', 'Штраф')], max_length=255, verbose_name='Причина начисления'),
        ),
    ]
