# Generated by Django 5.0.2 on 2024-05-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_user_type_alter_workerincomes_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('SALESMAN', 'Продавец'), ('FLORIST', 'Флорист с фиксированной платой'), ('FLORIST_PERCENT', 'Флорист с процентной платой'), ('MANAGER', 'Менеджер'), ('WAREHOUSE_MASTER', 'Зав. склад'), ('CRAFTER', 'Собиратель')], max_length=255, verbose_name='Тип пользователя'),
        ),
    ]
