# Generated by Django 5.0.2 on 2024-07-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerincomes',
            name='reason',
            field=models.CharField(choices=[('PRODUCT_SALE', 'Совершил/а продажу'), ('PRODUCT_FACTORY_SALE', 'Продался букет'), ('PRODUCT_FACTORY_CREATE', 'Создание букета')], max_length=255, verbose_name='Причина начисления'),
        ),
    ]
