# Generated by Django 5.0.2 on 2024-09-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_workerincomes_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_factory_create_commission',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=19, verbose_name='Сумма компенсации за создание букета'),
        ),
    ]
