# Generated by Django 5.0.2 on 2024-10-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_user_product_factory_create_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('SALESMAN', 'Продавец'), ('FLORIST', 'Флорист с фиксированной платой'), ('FLORIST_PERCENT', 'Флорист с процентной платой'), ('MANAGER', 'Менеджер'), ('WAREHOUSE_MASTER', 'Зав. склад'), ('CRAFTER', 'Собиратель'), ('NO_BONUS_SALESMAN', 'Продавец без зарплаты'), ('CASHIER', 'Кассир'), ('FLORIST_ASSISTANT', 'Помощник флориста'), ('INCOME_MANAGER', 'Закупщик'), ('OTHER', 'Прочие сотрудники')], max_length=255, verbose_name='Тип пользователя'),
        ),
    ]
