# Generated by Django 5.0.2 on 2024-02-22 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Баланс')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('ACCEPTED', 'Принят'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], default='CREATED', max_length=100, verbose_name='Статус')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Скидка')),
                ('total', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.client', verbose_name='Клиент')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
                ('count', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Кол-во')),
                ('total', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='order.order', verbose_name='Заказ')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='warehouse.warehouseproduct', verbose_name='Товар со склада')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
                'ordering': ['id'],
            },
        ),
    ]
