# Generated by Django 5.0.2 on 2024-03-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_department_order_department'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Долг'),
        ),
        migrations.CreateModel(
            name='OrderItemProductOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Количество')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_outcome', to='order.orderitem', verbose_name='Элемент заказа')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_outcome', to='warehouse.warehouseproduct', verbose_name='Товар')),
            ],
        ),
    ]
