# Generated by Django 5.0.2 on 2024-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_orderitem_warehouse_product_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='debt',
        ),
        migrations.AddField(
            model_name='order',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Долг'),
        ),
    ]
