# Generated by Django 5.0.2 on 2024-03-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orderitemproductoutcome_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], default='CREATED', max_length=100, verbose_name='Статус'),
        ),
    ]
