# Generated by Django 5.0.2 on 2024-03-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderitemproductreturn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemproductreturn',
            options={'ordering': ['-created_at'], 'verbose_name': 'Возврат товаров', 'verbose_name_plural': 'Возвраты товаров'},
        ),
    ]
