# Generated by Django 5.0.2 on 2024-03-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_orderitemproductreturn_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemproductreturn',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_returns', to='order.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
