# Generated by Django 5.0.2 on 2024-03-28 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_alter_productfactory_status'),
        ('order', '0018_orderitemproductreturn_deleted_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemProductFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_product_factory_set', to='order.order', verbose_name='Заказ')),
                ('product_factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_set', to='factory.productfactory', verbose_name='Товар из производства')),
            ],
            options={
                'verbose_name': 'Элемент заказа из произвдства',
                'verbose_name_plural': 'Элементы заказа из произвдства',
                'ordering': ['id'],
            },
        ),
    ]
