# Generated by Django 5.0.2 on 2024-03-28 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_orderitemproductfactory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemproductfactory',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Возвращен'),
        ),
        migrations.AddField(
            model_name='orderitemproductfactory',
            name='returned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_item_product_factory_set', to=settings.AUTH_USER_MODEL, verbose_name='Вернул'),
        ),
    ]
