# Generated by Django 5.0.2 on 2024-04-06 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_orderitemproductoutcome_warehouse_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemproductoutcome',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_outcomes', to='order.orderitem', verbose_name='Элемент заказа'),
        ),
    ]
