# Generated by Django 5.0.2 on 2024-04-08 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_orderitemproductoutcome_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemproductoutcome',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_outcomes', to='order.orderitem', verbose_name='Элемент заказа'),
        ),
    ]
