# Generated by Django 5.0.2 on 2024-04-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_orderitemproductfactory_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemproductfactory',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
    ]
