# Generated by Django 5.0.2 on 2024-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_order_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент скидки'),
        ),
    ]
