# Generated by Django 5.0.2 on 2025-06-22 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_client_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auto_discount_percent_change_enabled',
            field=models.BooleanField(default=True, verbose_name='Менять процент скидки автоматически'),
        ),
        migrations.CreateModel(
            name='ClientDiscountLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_sum_to', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Сумма покупок')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент скидки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_levels', to='order.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Настройка скидок клиенту',
                'verbose_name_plural': 'Настройка скидок клиентам',
                'ordering': ('orders_sum_to',),
            },
        ),
    ]
