# Generated by Django 5.0.2 on 2025-06-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_client_auto_discount_percent_change_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdiscountlevel',
            name='client',
        ),
    ]
