# Generated by Django 5.0.2 on 2024-02-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=19, verbose_name='Цена продажи'),
            preserve_default=False,
        ),
    ]
