# Generated by Django 5.0.2 on 2024-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Код'),
        ),
    ]
