# Generated by Django 5.0.2 on 2024-05-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='has_sale_compensation',
            field=models.BooleanField(default=True, verbose_name='Есть доля с продаж?'),
        ),
    ]
