# Generated by Django 5.0.2 on 2024-02-22 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('org_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Заметка')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_items', to='income.incomeitem', verbose_name='Приход')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_items', to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Элемент прихода',
                'verbose_name_plural': 'Элементы прихода',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('ACCEPTED', 'Принят'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], default='CREATED', max_length=255, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='income.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
                'ordering': ['-created_at'],
            },
        ),
    ]
