# Generated by Django 5.0.2 on 2024-02-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='incomeitem',
            name='income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_item_set', to='income.income', verbose_name='Приход'),
        ),
    ]
