# Generated by Django 5.0.2 on 2024-03-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_provider_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
