# Generated by Django 5.0.2 on 2024-04-22 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_alter_incomeitem_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='created_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
            preserve_default=False,
        ),
    ]
