# Generated by Django 5.0.2 on 2024-05-04 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_provider_created_user'),
        ('product', '0012_alter_product_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='product.product', verbose_name='Товар')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='income.provider', verbose_name='Поставщик')),
            ],
        ),
    ]
