# Generated by Django 5.0.2 on 2024-05-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0009_alter_providerproduct_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='total_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма цен продажи'),
        ),
        migrations.AddField(
            model_name='incomeitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='income',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма закупа'),
        ),
        migrations.AlterField(
            model_name='incomeitem',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='incomeitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Цена покупки'),
        ),
    ]
