# Generated by Django 5.0.2 on 2024-03-05 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('income', '0005_income_is_deleted'),
        ('order', '0007_department_order_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('outlay_type', models.CharField(choices=[('INVESTMENT', 'Инвестиция'), ('SPENDING', 'Затраты')], max_length=255, verbose_name='Тип расходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outlays', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Причина расхода',
                'verbose_name_plural': 'Причины расхода',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('payment_method', models.CharField(choices=[('CASH', 'Наличными'), ('CARD', 'Картой'), ('TRANSFER', 'Перечисление'), ('TRANSFER_TO_CARD', 'Перевод на карту')], max_length=255, verbose_name='Метод оплаты')),
                ('payment_type', models.CharField(choices=[('INCOME', 'Доход'), ('OUTCOME', 'Расход')], max_length=255, verbose_name='Доход/Расход')),
                ('payment_model_type', models.CharField(choices=[('OUTLAY', 'Расходы'), ('ORDER', 'Заказ'), ('INCOME', 'Приход'), ('PROVIDER', 'Поставщик')], max_length=255, verbose_name='Тип оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='order.client', verbose_name='Клиент')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='income.income', verbose_name='Приход')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='order.order', verbose_name='Заказ')),
                ('outlay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment.outlay', verbose_name='Расход')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='income.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-id'],
            },
        ),
    ]
