# Generated by Django 5.0.2 on 2024-03-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier_type', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('BANK', 'Банк')], max_length=255, verbose_name='Тип кассы')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
            },
        ),
    ]
