# Generated by Django 5.0.2 on 2024-03-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_cashier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма'),
        ),
    ]
