# Generated by Django 5.0.2 on 2024-03-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_deleted_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashier',
            options={'ordering': ['id'], 'verbose_name': 'Касса', 'verbose_name_plural': 'Кассы'},
        ),
    ]
