# Generated by Django 5.0.2 on 2024-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_worker_alter_payment_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='outlay_type',
            field=models.CharField(choices=[('INVESTMENT', 'Инвестиция'), ('SPENDING', 'Затраты'), ('WORKERS', 'Сотрудники')], max_length=255, verbose_name='Тип расходов'),
        ),
    ]
