# Generated by Django 5.0.2 on 2024-05-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_paymentmethodcategory_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method_temp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payment.paymentmethod', verbose_name='Метод оплаты'),
        ),
    ]
