# Generated by Django 5.0.2 on 2024-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_cashier_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Наличными'), ('CARD', 'Картой'), ('TRANSFER', 'Перечисление'), ('TRANSFER_TO_CARD', 'Перевод на карту')], max_length=255, null=True, verbose_name='Метод оплаты'),
        ),
    ]
