# Generated by Django 5.0.2 on 2024-05-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashier',
            name='cashier_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
