# Generated by Django 5.0.2 on 2024-05-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_remove_cashier_cashier_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method_temp',
            new_name='payment_method',
        ),
    ]
