# Generated by Django 5.0.2 on 2024-05-18 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_cashiershift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashiershift',
            options={'ordering': ['-start_date'], 'verbose_name': 'Смена кассы', 'verbose_name_plural': 'Смены кассы'},
        ),
    ]
