# Generated by Django 5.0.2 on 2024-05-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_cashiershift_options'),
        ('product', '0014_alter_product_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlay',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlays', to='product.industry', verbose_name='Отрасль'),
        ),
    ]
