# Generated by Django 5.0.2 on 2024-06-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_outlay_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiershift',
            name='cash_income_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма прихода (наличные)'),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='cash_outcome_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма расхода (наличные)'),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='overall_income_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма расхода'),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='overall_outcome_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма расхода'),
        ),
    ]
