# Generated by Django 5.0.2 on 2025-03-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
    ]
