# Generated by Django 5.0.2 on 2024-02-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.industry', verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Категория'),
        ),
    ]
