# Generated by Django 5.0.2 on 2024-03-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_is_deleted_industry_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_composite',
            field=models.BooleanField(default=False, verbose_name='Составной'),
        ),
    ]
