# Generated by Django 5.0.2 on 2024-04-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_is_composite'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_for_sale',
            field=models.BooleanField(default=True, verbose_name='На продажу'),
        ),
    ]
