# Generated by Django 5.0.2 on 2024-04-22 04:32

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_is_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=60, scale=None, size=[512, 512], upload_to='images/products/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
