# Generated by Django 5.0.2 on 2024-05-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('PIECE', 'шт.'), ('METER', 'м.'), ('CENTIMETER', 'см.'), ('BRANCH', 'ветка')], default='PIECE', max_length=50, verbose_name='Ед. измерения'),
        ),
    ]
