# Generated by Django 5.0.2 on 2024-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_industry_has_sale_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('PIECE', 'шт.'), ('METER', 'м.'), ('CENTIMETER', 'см.'), ('BRANCH', 'ветка'), ('PACKAGE', 'Пачка')], default='PIECE', max_length=50, verbose_name='Ед. измерения'),
        ),
    ]
