# Generated by Django 5.0.2 on 2024-05-26 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='sale_compensation_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент с продажи продавцу'),
        ),
    ]
