# Generated by Django 5.0.2 on 2024-02-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_total_alter_incomeitem_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Баланс'),
        ),
    ]
