# Generated by Django 5.0.2 on 2024-03-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_provider_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
