# Generated by Django 5.0.2 on 2024-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_income_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма'),
        ),
    ]
