# Generated by Django 5.0.2 on 2024-05-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0008_providerproduct'),
        ('product', '0012_alter_product_unit_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerproduct',
            unique_together={('product', 'provider')},
        ),
    ]
