# Generated by Django 5.0.2 on 2024-05-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0010_income_total_sale_price_incomeitem_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeitem',
            name='total_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма цен продаж'),
        ),
    ]
