# Generated by Django 5.0.2 on 2024-03-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseproduct',
            options={'ordering': ['product', '-count'], 'verbose_name': 'Товар из склада', 'verbose_name_plural': 'Товары из склада'},
        ),
    ]
