# Generated by Django 5.0.2 on 2024-03-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_warehouseproductwriteoff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseproductwriteoff',
            options={'ordering': ['-created_at'], 'verbose_name': 'Списание товара', 'verbose_name_plural': 'Списания товаров'},
        ),
    ]
