# Generated by Django 5.0.2 on 2024-05-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_warehouseproduct_income_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Цена продажи'),
        ),
    ]
