# Generated by Django 5.0.2 on 2024-06-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_warehouseproduct_sale_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар из склада', 'verbose_name_plural': 'Товары из склада'},
        ),
    ]
