# Generated by Django 5.0.2 on 2024-04-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_settings_congratulations_product_factory_sale_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='product_factory_create_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма компенсации за создание букета'),
        ),
    ]
