# Generated by Django 5.0.2 on 2024-05-18 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_settings_multiple_product_sale_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='product_factory_charge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент наценки на букет'),
        ),
    ]
