# Generated by Django 5.0.2 on 2024-05-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_settings_congratulations_sweets_create_commission_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='product_factory_charge_percent',
        ),
    ]
