# Generated by Django 5.0.2 on 2024-05-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_settings_product_factory_charge_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='multiple_product_sale_commission_percentage',
        ),
    ]
