# Generated by Django 5.0.2 on 2024-11-01 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_settings_write_off_permission_granted_industries'),
        ('warehouse', '0007_alter_warehouseproduct_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('PRODUCT_WRITE_OFF', 'Списание товара')], max_length=50, verbose_name='Тип запроса')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Доставлен')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Отвечен')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Разрешение дано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('wh_product_write_off', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_requests', to='warehouse.warehouseproductwriteoff', verbose_name='Списание товара')),
            ],
        ),
    ]
