# Generated by Django 5.0.2 on 2025-03-31 05:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_permissionrequesttgmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='permission_notification_receivers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None, verbose_name='ТГ аккаунты которым приходит оповещения о подтверждении'),
        ),
    ]
