# Generated by Django 5.0.2 on 2024-02-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Кол-во')),
                ('self_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Себестоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_products', to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар из склада',
                'verbose_name_plural': 'Товары из склада',
                'ordering': ['-created_at'],
            },
        ),
    ]
