# Generated by Django 5.0.2 on 2024-03-23 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_warehouseproduct_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProductWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Кол-во')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_created_write_offs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_user_write_offs', to=settings.AUTH_USER_MODEL, verbose_name='Удален')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_write_off_set', to='warehouse.warehouseproduct', verbose_name='Товар со склада')),
            ],
        ),
    ]
