# Generated by Django 5.0.2 on 2024-04-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_alter_incomeitem_total'),
        ('warehouse', '0004_alter_warehouseproductwriteoff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='income_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='income.incomeitem', verbose_name='Элемент прихода'),
            preserve_default=False,
        ),
    ]
