# Generated by Django 5.0.2 on 2024-05-04 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_payment_payment_method_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashiers', to='payment.paymentmethod', verbose_name='Метод оплаты'),
        ),
    ]
