# Generated by Django 5.0.2 on 2024-05-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_cashier_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='cashier_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('BANK', 'Банк')], max_length=255, null=True, verbose_name='Тип кассы'),
        ),
    ]
