# Generated by Django 5.0.2 on 2024-05-04 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_cashier_cashier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashiers', to='payment.paymentmethod', verbose_name='Тип кассы'),
        ),
    ]
