# Generated by Django 5.0.2 on 2024-05-17 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_rename_payment_method_temp_payment_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата конца')),
                ('completed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл смену')),
                ('started_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Открыл смену')),
            ],
            options={
                'verbose_name': 'Смена кассы',
                'verbose_name_plural': 'Смены кассы',
                'ordering': ['-started_user'],
            },
        ),
    ]
