# Generated by Django 5.0.2 on 2024-07-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_cashiershift_cash_income_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_debt',
            field=models.BooleanField(default=False, verbose_name='Оплата долга'),
        ),
    ]
