# Generated by Django 5.0.2 on 2024-10-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_payment_is_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
