# Generated by Django 5.0.2 on 2024-03-26 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_productfactory_type'),
        ('product', '0006_category_is_deleted_industry_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_factory_set', to='product.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
