# Generated by Django 5.0.2 on 2024-03-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_productfactory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfactory',
            name='type',
        ),
    ]
