# Generated by Django 5.0.2 on 2024-03-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_alter_productfactory_self_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactoryitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма'),
        ),
    ]
