# Generated by Django 5.0.2 on 2024-03-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_productfactoryitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfactoryitem',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Кол-во'),
        ),
    ]
