# Generated by Django 5.0.2 on 2024-04-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_alter_productfactory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFactoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория произведенных товаров',
                'verbose_name_plural': 'Категории произведенных товаров',
            },
        ),
    ]
