# Generated by Django 5.0.2 on 2024-04-01 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0014_productfactorycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfactory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_factory_set', to='factory.productfactorycategory', verbose_name='Категория'),
        ),
    ]
