# Generated by Django 5.0.2 on 2024-04-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0015_alter_productfactory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfactory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Производство товара', 'verbose_name_plural': 'Производство товаров'},
        ),
        migrations.AddField(
            model_name='productfactory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
