# Generated by Django 5.0.2 on 2024-04-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0017_productfactory_florist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactory',
            name='sales_type',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('FINISHED', 'Завершен'), ('SOLD', 'Продан'), ('WRITTEN_OFF', 'Списан')], default='STORE', max_length=255, verbose_name='Тип продажи товара'),
            preserve_default=False,
        ),
    ]
