# Generated by Django 5.0.2 on 2024-04-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0020_remove_productfactoryitem_total_and_more'),
        ('warehouse', '0004_alter_warehouseproductwriteoff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfactoryitem',
            name='warehouse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_factory_item_set', to='warehouse.warehouseproduct', verbose_name='Товар со склада'),
        ),
    ]
