# Generated by Django 5.0.2 on 2024-04-24 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0022_alter_productfactory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFactoryItemReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('count', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Кол-во')),
                ('total_self_price', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма себестоимости')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_factory_returns_created_users', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_factory_returns_deleted_users', to=settings.AUTH_USER_MODEL, verbose_name='Удалил')),
                ('factory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_returns', to='factory.productfactoryitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
