# Generated by Django 5.0.2 on 2024-04-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0025_productfactoryitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfactoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Цена'),
        ),
    ]
