# Generated by Django 5.0.2 on 2024-04-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0026_alter_productfactoryitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactory',
            name='written_off_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата списания'),
        ),
    ]
