# Generated by Django 5.0.2 on 2024-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0027_productfactory_written_off_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfactory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
