# Generated by Django 5.0.2 on 2024-05-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0029_productfactory_is_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfactory',
            name='is_penalty',
        ),
    ]
