# Generated by Django 5.0.2 on 2024-05-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0030_remove_productfactory_is_penalty'),
        ('product', '0013_industry_has_sale_compensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactorycategory',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.industry', verbose_name='Отрасль'),
        ),
    ]
