# Generated by Django 5.0.2 on 2024-10-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0033_factorytakeapartrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorytakeapartrequest',
            name='initial_status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('FINISHED', 'Завершен'), ('SOLD', 'Продан'), ('PENDING', 'В ожидании разборки'), ('WRITTEN_OFF', 'Списан')], default='FINISHED', max_length=50, verbose_name='Статус при запросе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factorytakeapartrequest',
            name='request_type',
            field=models.CharField(choices=[('TO_CREATE', 'Разборка'), ('WRITE_OFF', 'Списание')], default='TO_CREATE', max_length=50, verbose_name='Тип запроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productfactory',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('FINISHED', 'Завершен'), ('SOLD', 'Продан'), ('PENDING', 'В ожидании разборки'), ('WRITTEN_OFF', 'Списан')], default='CREATED', max_length=255, verbose_name='Статус'),
        ),
    ]
