# Generated by Django 5.0.2 on 2025-06-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0035_alter_factorytakeapartrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorytakeapartrequest',
            name='request_type',
            field=models.CharField(choices=[('TO_CREATE', 'Разборка'), ('WRITE_OFF', 'Списание')], max_length=50, verbose_name='Тип запроса'),
        ),
    ]
